### ISSUE TITLE
How to make it suitable for my own PC

### ISSUE THREAD

**Issue by RockJesus** [hieplpvip/AsusSMC#1]
Hi,This's a great work,and I wish i could have the same function on my Alienware 17 R4.
Any help will be Appreciated.
Could u share ur acpi tables & ioreg files ,Thx.

**Comment by hieplpvip** [comment]
Send me your ACPI, I'll tell you where you need to look into

**Comment by RockJesus** [comment]
Here it is。

[alienware17r4acpi.zip](https://github.com/hieplpvip/AsusSMC/files/2486551/alienware17r4acpi.zip)

**Comment by hieplpvip** [comment]
Alienware is not Asus laptop. Closed
