### ISSUE TITLE
another cpu

### ISSUE THREAD

**Issue by mastermoon76** [hieplpvip/AsusSMC#10]
hello, i'm using an asus N551JW with an i7-4720HQ Haswell CPU... attached you will find the DSDT file.. hope you can make the patch for this model.. thank you... 
[DSDT.aml.zip](https://github.com/hieplpvip/AsusSMC/files/2863399/DSDT.aml.zip)

**Comment by hieplpvip** [comment]
Please use patch "[kbl] Haswell/Broadwell/Skylake"
