### ISSUE TITLE
Patch DSDT giúp mình với bạn ơi

### ISSUE THREAD

**Issue by wanttolove** [hieplpvip/AsusSMC#12]
[Send me macs-MacBook-Pro.zip](https://github.com/hieplpvip/AsusSMC/files/3104704/Send.me.macs-MacBook-Pro.zip)
Mình patch cái kbl của bạn vào thì báo lỗi WRAM is not accessible from this scope. Bấm fn+f3 thì vẫn nhảy popup bình thường nhưng ko có tác dụng gì cả. Thanks

**Comment by hieplpvip** [comment]
Bạn dùng patch của Broadwell nha

**Comment by hieplpvip** [comment]
Mình update patch rồi đó bạn. Bạn thử lại nha

**Comment by wanttolove** [comment]
Lần này thì nó ko báo lỗi nữa nhưng vẫn như cũ bấm hiện ra nhưng ko tác dụng gì. windows vẫn sử dụng đc. đã thử cả 3 patch broadwell, kaby với cả whiskey. máy mình là kaby-R

**Comment by hieplpvip** [comment]
Gửi mình file debug theo link này: https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/

**Comment by wanttolove** [comment]
[debug_24314.zip](https://github.com/hieplpvip/AsusSMC/files/3145646/debug_24314.zip)
đây b ơi. thanks

**Comment by hieplpvip** [comment]
[DSDT.aml.zip](https://github.com/hieplpvip/AsusSMC/files/3145691/DSDT.aml.zip)

Bạn xoá kext AsusNBFnKeys nha.

**Comment by wanttolove** [comment]
ok được rồi thank bạn nhiều nhé. vn no1 :D
