### ISSUE TITLE
Không điều chỉnh được Keyboard Backlight máy S530UN, bản KabylakeR

### ISSUE THREAD

**Issue by tunglamvghy** [hieplpvip/AsusSMC#17]
Bác Hiệp cho e xin cách sửa với. Máy đã làm theo hướng dẫn nhưng không thể tắt được đèn nền bàn phím, nó ở chế độ luôn luôn sáng.
ACPIDebug:
Fn + F1: mute
Fn + F2: giảm âm
Fn + F3: tăng âm
Fn + F4: giảm ánh sáng => _Q0E  <hoạt động tốt>
Fn + F5: tăng ánh sáng => _Q0F   <hoạt động tốt>
Fn + F6: tắt Touchpad => _Q12
Fn + F7: bật đèn nền bàn phím => _Q0D <không hoạt động>
Fn + F8: máy chiếu => _Q11 <chưa thử>
Fn + Esc: tắt phím Fn => _QD5
Fn + Enter(phụ): mở máy tính => _Q77
Fn + Space: ko biết => _Q71
Mong bác sửa giúp e với
[DSDT copy.dsl.zip](https://github.com/hieplpvip/AsusSMC/files/3177108/DSDT.copy.dsl.zip)

**Comment by hieplpvip** [comment]
Dùng patch `[kbl] Kaby Lake/Kaby Lake-R`. Lúc này nhấn Fn+F7 sẽ tăng level đèn bàn phím.

Vì máy bạn chỉ có một phím Fn cho đèn bàn phím nên bạn cần map thêm phím thứ hai: Dùng Karabiner map phím F7 thành illumination_decrement.

Kết quả: Fn+F7->tăng; F7->giảm
