### ISSUE TITLE
just a question, what is als and how to check it ?

### ISSUE THREAD

**Issue by souhaiebtar** [hieplpvip/AsusSMC#19]

**Comment by hieplpvip** [comment]
ALS stands for "Ambient Light Sensor", which detects light level and adjust screen backlight automatically.

To check ALS, download debug version, add boot arg `-asussmcdbg`. Reboot, open `Console` then search for `AsusSMC` or `als` (not sure which one, sorry)

**Comment by souhaiebtar** [comment]
thanks
