### ISSUE TITLE
Just a few questions...

### ISSUE THREAD

**Issue by zacharyrs** [hieplpvip/AsusSMC#2]
I currently use EMlyDinEsHMG's kexts for keyboard and touchpad, but considering they haven't been updated in a while, I'm eager for an alternative. I assume that this kext would hence replace the keyboard portions, but would not help regarding the touchpad.

I'm just wondering if you hence use EMlyDinEsHMG's touchpad parts, or perhaps you could point me in the direction of an alternative?

Also, am I right to assume with this I would not need your AsusFnKeys driver?

Lastly, are the DSDT patches simply like those required by EMlyDinEsHMG's kexts, or are they different?

Thanks!

**Comment by hieplpvip** [comment]
1. It seems like you're misunderstanding AsusSMC. To be clear, it has nothing to do with keyboard support. AsusSMC only adds support for ALS and keyboard backlight, as well as Fn keys. You still need a keyboard kext (eg. VoodooPS2Controller or EMlyDinEsHMG's kexts).

2. I assume you have PS/2 trackpad. EMlyDinEsHMG's kexts are the best one now, you should continue using them.

3. AsusSMC is a replacement for AsusFnKeys

4. DSDT patches are different. I don't have time to write an instruction now, sorry.

**Comment by zacharyrs** [comment]
Hi, thanks for the response!

1. I apologise for the misunderstanding, but thanks for clarifying it.

2. Yes I do have a PS/2 trackpad. Guess I'll just wait it out for EMlyDinEsHMG to release the source...

3. I see, that makes sense.

4. No worries! Any chance you'd feel comfortable releasing your original and patched DSDT, so I can take a look and try reverse the patches for my own? No pressure though - if you don't want to I'll just wait it out.

**Comment by hieplpvip** [comment]
Take a look at my repo for Asus Zenbook https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH

**Comment by zacharyrs** [comment]
Thanks for the link! Probably should've looked at your profile myself oops...

Just having had a skim, I assume the following are files of interest:
- SSDT-ALS0
- SSDT-ALSC
- SSDT-RALS
- SSDT-ATK-BDW
- SSDT-ATK-KABY

Regarding ALS0, ALSC and RALS, I have no ambient light sensor, so would I be correct to assume I don't need any of these? Or do I hence need ALS0 to fake one as per the S510?

Regarding ATK-BDW and ATK-KABY, I assume I would need to develop my own, for Haswell?
My own DSDT methods appear similar to BDW in that there's no PCI0.LPCB.EC0.ST9E method, however dissimilar in the SLKB method... Do I simply copy my own methods here?


Lastly, sorry for the repeated queries, I think I should be able to figure it out from here!

**Comment by hieplpvip** [comment]
What is your laptop?

**Comment by zacharyrs** [comment]
Asus GL551JW

**Comment by hieplpvip** [comment]
Send me your CLVOER folder with original ACPI files

**Comment by zacharyrs** [comment]
Sorry for the delay, I've been a little caught up with exams.
Attached is an archive of my clover config, and ACPI files.
The original source for my patches is found [here](https://github.com/zacharyrs/GL551JW-Hackintosh).

[CLOVER.zip](https://github.com/hieplpvip/AsusSMC/files/2535067/CLOVER.zip)

**Comment by hieplpvip** [comment]
@zacharyrs Instruction is available in the Wiki

**Comment by zacharyrs** [comment]
Thanks very much!

I'll give it a go tonight.

**Comment by zacharyrs** [comment]
Sorry for the delay, got a little distracted...

I've just tried applying, as per the hotpatches available in my repo.
[You can view them here.](https://github.com/zacharyrs/GL551JW-Hackintosh)

Unfortunately I'm running into a little trouble with the FN keys.
Specifically when I don't apply any of the function key patches, F1, F2, F5, F6, F8, and F9 don't work.
When I do apply the patches, the above still don't work, but F3 and F4 stop too.

I'm probably making a silly mistake, but any chance you could take a look?

On a sidenote, if I wanted only 4 brightness levels for the backlight, would it only be a matter of changing PWKB and the first line in the following method (Arg0 / 16 to Arg0 / 4)?

**Comment by zacharyrs** [comment]
I've been trying to figure out what I might be doing wrong, and I noticed you have an I2C as opposed to PS2 trackpad.

Is this perhaps incompatible with ApplePS2SmartTouchpad? I have removed AsusNBFNKey, and disabled the related sections...

---

I tried installing the debug variant, enabled the clover patches again and started playing around...

The following is logged for F3 and F4:
```
AsusSMC:     atk @ (DBG) Received Key 0(0x0)
AsusSMC:     atk @ (DBG) Unknown key 00 i=14
```

F5 and F6 do nothing.

F7 outputs (note this is for two presses):
```
AsusSMC:     atk @ (DBG) Failed to find backlight entry for IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/GFX0@2/AppleIntelFramebuffer@0/display0/AppleBacklightDisplay
AsusSMC:     atk @ (DBG) Panel brightness level from AppleBacklightDisplay: 817
AsusSMC:     atk @ (DBG) Read panel brightness level: 12
AsusSMC:     atk @ (DBG) Received Key 32(0x20)
AsusSMC:     atk @ (DBG) Key Pressed 20 i=5
AsusSMC:     atk @ (DBG) Loop Count -1, Dispatch Key 32(0x20)
AsusSMC:     atk @ (DBG) Received Key 16(0x10)
AsusSMC:     atk @ (DBG) Key Pressed 10 i=4
AsusSMC:     atk @ (DBG) Loop Count -1, Dispatch Key 16(0x10)
```

F8 outputs nothing.

F9 outputs the following (but the touchpad remains enabled anyway):
```
AsusSMC:     atk @ (DBG) Touchpad Disabled
AsusSMC:     atk @ (DBG) Received Key 107(0x6b)
AsusSMC:     atk @ (DBG) Unknown key 6B i=14
AsusSMC:     atk @ (DBG) Touchpad Enabled
AsusSMC:     atk @ (DBG) Received Key 107(0x6b)
AsusSMC:     atk @ (DBG) Unknown key 6B i=14
```

F10, F11, and F12 work.

**Comment by hieplpvip** [comment]
@zacharyrs I have updated the instruction, you may want to try again

**Comment by zacharyrs** [comment]
@hieplpvip 	I'll take at them soon, and see if I can spot what went wrong.
Just a little bogged down with other stuff right now.

For now I'll mark this as closed.
