### ISSUE TITLE
Can't save keyboard light to 0 upon reboot/shutdown

### ISSUE THREAD

**Issue by ghost** [hieplpvip/AsusSMC#25]
Hi, thanks for this kext. There's only one thing bothering me, I can't set keyboard backlight to 0 (turned off) when I restart (I hate keyboard light when I don't need it). If I set other levels (1-2-3-4), that level is saved upon restart. Is it solvable?

**Comment by hieplpvip** [comment]
AsusSMC only serves as the interface of macOS and ACPI. It doesn't store keyboard backlight.
This should be a problem with how macOS handle keyboard backlight. Closed.
