### ISSUE TITLE
VirtualSMCSDK/kern_vsmcapi.hpp' file not found

### ISSUE THREAD

**Issue by JoK3rLeE** [hieplpvip/AsusSMC#26]
Failed to build, Error 
VirtualSMCSDK/kern_vsmcapi.hpp' file not found.

**Comment by hieplpvip** [comment]
You don't have debug versions of `VirtualSMC` and `Lilu` in root folder of `AsusSMC`.

To download them automatically, run `sh Scripts/bootstrap.sh`.
