### ISSUE TITLE
GL553VD

### ISSUE THREAD

**Issue by MohammadtaghiFarkhondekar** [hieplpvip/AsusSMC#27]
HI.
please add Asus Aura core for the laptop to your kexts bc aura keyboard backlight doesn't work.

**Comment by MohammadtaghiFarkhondekar** [comment]
https://github.com/wroberts/rogauracore/issues/4
https://github.com/wroberts/rogauracore

https://linux-hardware.org/index.php?id=usb:0b05-1854

**Comment by hieplpvip** [comment]
Test this one please [1.2.0.RELEASE.zip](https://files.gitter.im/hieplpvip/AsusSMC/vvPz/1.2.0.RELEASE.zip)

**Comment by MohammadtaghiFarkhondekar** [comment]
Thank you . Does it need to patching for working ?

**Comment by MohammadtaghiFarkhondekar** [comment]
Ok . I test it without any patching .
F1+FN working good
F2+FN I think working bc I haven't wifi card for set it on turn off mode.
F3 and F4 aren't working 
F5 and F6 are working so good but F14 and F15 alsoe are working
F7 is working 
F8 I think it doesn't working .
F9 is working but without showing the system notification for turn off track pad.
F10,F11,F12 are working good.
Can you make Aura core control for Mac OS ?
Thank you .

**Comment by hieplpvip** [comment]
On Windows/Linux, Aura driver sends commands to the keyboard through the USB protocol.
Unfortunately, I've not figured out how to to it properly on macOS, so keyboard backlight is not working now.

**Comment by MohammadtaghiFarkhondekar** [comment]
That's right . Aura core has open source project in GitHub I think it can help for fixing .
In Mac OS it's connected by usb , name ITE Device (8910).
Product ID : 0x1854

**Comment by MohammadtaghiFarkhondekar** [comment]
https://www.asus.com/campaign/aura/fl/Partners-and-promotions.html

**Comment by hieplpvip** [comment]
I've already known all you said...

**Comment by MohammadtaghiFarkhondekar** [comment]
https://gitlab.com/thelastguardian/openpyaura

https://github.com/CalcProgrammer1/KeyboardVisualizer

**Comment by hieplpvip** [comment]
[rogauracore.zip](https://github.com/hieplpvip/AsusSMC/files/3404755/rogauracore.zip)

Hi @MohammadtaghiFarkhondekar, can you test this? It's compiled for macOS from source code of rogauracore that you gave

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi. Thank you so much. how can I test it?
I opened it =>
![Screen Shot 1398-04-27 at 12 11 08](https://user-images.githubusercontent.com/35239600/61438972-dd340900-a955-11e9-8951-436322fa16f3.png)

**Comment by hieplpvip** [comment]
Another one has tested it and confirmed it doesn't work...

**Comment by MohammadtaghiFarkhondekar** [comment]
I tested ubuntu 18.04 and it have Aura driver and it can control keyboard backlight.
https://linux-hardware.org/index.php?id=usb:0b05-1854

**Comment by hieplpvip** [comment]
Test this [one](https://files.gitter.im/hieplpvip/AsusSMC/O3yC/1.2.0.RELEASE.zip)

Note that macOS supports 16 levels, while your keyboard only support 4 level, so:
- Level 0-4 of macOS -> level 0 of your keyboard
- Level 5-8 of macOS -> level 1 of your keyboard
- Level 9-12 of macOS -> level 2 of your keyboard
- Level 13-16 of macOS -> level 3 of your keyboard

**Comment by MohammadtaghiFarkhondekar** [comment]
Thank you. just replace kext?
I replaced kext and reboot again but keybord backlight with FN key (f3,f4) doesn't work.

**Comment by hieplpvip** [comment]
Where do you install kexts?
If it is /L/E, have you rebuilt kext cache?

**Comment by MohammadtaghiFarkhondekar** [comment]
Clover folder . Need to install in the system ?

**Comment by hieplpvip** [comment]
CLOVER should be good.
Please send me your IOReg

**Comment by MohammadtaghiFarkhondekar** [comment]
Ok. I'm going to get file now and send it

**Comment by MohammadtaghiFarkhondekar** [comment]
[MacBook Pro-rog553vd.zip](https://github.com/hieplpvip/AsusSMC/files/3407306/MacBook.Pro-rog553vd.zip)

**Comment by hieplpvip** [comment]
@MohammadtaghiFarkhondekar Does the badge show up when you press Fn+F3/F4?

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi. No. Any things don't show when I press FN+F3/F4. But
System doesn't play sound about without commend key .

**Comment by williambj1** [comment]
> Hi. Thank you so much. how can I test it?
> I opened it =>
> ![Screen Shot 1398-04-27 at 12 11 08](https://user-images.githubusercontent.com/35239600/61438972-dd340900-a955-11e9-8951-436322fa16f3.png)

Seems that you're missing libusb, :)
`brew install libusb` should solve that error.
However, I've confirmed that this didn't work for me. Some people say that libusb is dead on macOS Mojave, currently, I don't have HS.

**Comment by hieplpvip** [comment]
@MohammadtaghiFarkhondekar [1.2.0.RELEASE.zip](https://github.com/hieplpvip/AsusSMC/files/3409591/1.2.0.RELEASE.zip)

**Comment by MohammadtaghiFarkhondekar** [comment]
Oh my God . Woooooooooooow . Thank you so much . Your work is so nice. 
Now keyboard backlight working great but without  showing badge like touchpad (F9).
Can you make manager app for Aura core like Linux project ? 
Thank you

**Comment by hieplpvip** [comment]
@MohammadtaghiFarkhondekar will do when I have time, not now sorry

**Comment by MohammadtaghiFarkhondekar** [comment]
Thank you, your project link add to [https://github.com/MohammadtaghiFarkhondekar/macOS-Mojave-For-Asus-ROG-GL553VD/blob/master/README.md](url)

**Comment by hieplpvip** [comment]
[ROGAuraCore.zip](https://github.com/hieplpvip/AsusSMC/files/3413504/ROGAuraCore.zip)
@MohammadtaghiFarkhondekar test this

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi.
![Screen Shot 1398-04-29 at 15 24 12](https://user-images.githubusercontent.com/35239600/61577862-815ab300-ab02-11e9-93fd-251d441a902e.png)
 thank you. how can I use it?

**Comment by MohammadtaghiFarkhondekar** [comment]
woooooorking

**Comment by MohammadtaghiFarkhondekar** [comment]
![Screen Shot 1398-04-29 at 15 30 16](https://user-images.githubusercontent.com/35239600/61577909-558bfd00-ab03-11e9-90de-6598cde8c5cd.png)
can you make UI for it?

**Comment by MohammadtaghiFarkhondekar** [comment]
wooooooooooooooooow . its wooooooooork soooooo goooooooooooooood . 
it's need UI . it's better than asus app for aura !
it's the first app for aura for mac on the word by you!

**Comment by hieplpvip** [comment]
@MohammadtaghiFarkhondekar I've published the program at [macrogaura](https://github.com/hieplpvip/macrogaura/)

I'm not good at designing UI. You'd better wait for someone else to do it.

**Comment by MohammadtaghiFarkhondekar** [comment]
it's a good app. thank you for making it. 
I think it doesn't need pro UI  .
Asus aura core app in windows 
![image](https://user-images.githubusercontent.com/35239600/61583336-1df57300-ab4c-11e9-96f1-9e031872054a.png)

**Comment by MohammadtaghiFarkhondekar** [comment]
I add your project to gl553vd page and I will make a video about it .

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi .
How are you good developer ?
Now in 10.15 , Asus smc doesn't working and when I use it my keyboard doesn't working !
