### ISSUE TITLE
Can't find 'ALS' in the 'DSDT'

### ISSUE THREAD

**Issue by wr-yt** [hieplpvip/AsusSMC#28]
My noteBook is FX80GE(FX504GE),I don't find 'ALS' in the 'DSDT',but I  find 'ALSC' and 'ALSS'.when  apply patch [als] Patch ALSS ,There was a mistake in the 'DSDT'
[DSDT.txt](https://github.com/hieplpvip/AsusSMC/files/3444576/DSDT.txt)

This is my DSDT
when my kext has voodooI2c ，F7 and F8 can't work,。Just now,The arrow of the picture arrow has no effect。
![QQ20190730-080155](https://user-images.githubusercontent.com/32641588/62090731-7ccf9080-b2a0-11e9-8595-4bd597171499.png)

**Comment by williambj1** [comment]
ROG Keyboards have different key caps :)

**Comment by wr-yt** [comment]
Can this product only be used in the ROG series?


------------------ 原始邮件 ------------------
发件人: "Bat.bat"<notifications@github.com>;
发送时间: 2019年7月30日(星期二) 上午8:45
收件人: "hieplpvip/AsusSMC"<AsusSMC@noreply.github.com>;
抄送: "坚持之薰衣草"<1679227405@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hieplpvip/AsusSMC] Can't find 'ALS' in the 'DSDT' (#28)




ROG Keyboards have different key caps :)

**Comment by wr-yt** [comment]
These two files will conflict ，the voodooI2c ,the ASUSSMC

**Comment by williambj1** [comment]
I suppose it's not an issue caused by VoodooI2C, I have the same keycaps as yours (ROG) and all Fn keys work well on the correct keycaps.

- Chinese Translation
>
> 我觉得应该不是 VoodooI2C 的问题，我的键帽和你的一样，都是 ROG，而且所有的 Fn 键都正常工作在正确的键位上

**Comment by wr-yt** [comment]
You are right. But my touchpad feels a bit stuttering, what is the problem?




------------------ 原始邮件 ------------------
发件人: "Bat.bat"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 中午11:03
收件人: "hieplpvip/AsusSMC"<AsusSMC@noreply.github.com>;
抄送: "坚持之薰衣草"<1679227405@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hieplpvip/AsusSMC] Can't find 'ALS' in the 'DSDT' (#28)




I suppose it's not an issue caused by VoodooI2C, I have the same keycaps as yours (ROG) and all Fn keys work well on the correct keycaps.
  
Chinese Translation
   
我觉得应该不是 VoodooI2C 的问题，我的键帽和你的一样，都是 ROG，而且所有的 Fn 键都正常工作在正确的键位上
