### ISSUE TITLE
I say..

### ISSUE THREAD

**Issue by wr-yt** [hieplpvip/AsusSMC#29]
I also want to give you financial support, but I am in China, basically using Alipay WeChat, please understand. Also as a developer, like you

**Comment by hieplpvip** [comment]
Hello @angeljavan,

I created this kext not only to finalize my Hackintosh build, but also to contribute back to the Hackintosh community. Without this community, I would never be able to install macOS on my laptop.

Donation is welcome but never required. I'll always keep this kext free and open-source, and I'll try to update it as long as possible.

I'm very happy to know that my kext is helpful for you.
