### ISSUE TITLE
DSDT and laptop compatibility

### ISSUE THREAD

**Issue by Xapixowy** [hieplpvip/AsusSMC#3]
For a month i'm a proud owner of my new Asus Vivobook R520UF (X510UF). Does AsusSMC will be compatible with my laptop? There's a one thing stopping me from install Hackintosh - keyboard hotkeys (generally screen brightness and volume). I'm waiting for this plugin so much. Can I expect a DSDT patching guide this year?

**Comment by hieplpvip** [comment]
I'm pretty busy now, not sure when I can write the guide.

**EDIT:** The instruction is available in the Wiki
