### ISSUE TITLE
Add support for Ivy Bridge keyboard backlight

### ISSUE THREAD

**Issue by ulf16** [hieplpvip/AsusSMC#44]
I'd love to see this wonderful kext having kbl support for my old but trusty Ivy Bridge based N56VM.

[DSDT.aml.zip](https://github.com/hieplpvip/AsusSMC/files/3747786/DSDT.aml.zip)

**Comment by ulf16** [comment]
Never mind, the solution for me is to use the Haswell patches and changing 
^^PCI0.LPCB.EC0.WRAM (0x04B1, Arg0)\n
to
^^PCI0.LPCB.EC0.WRAM (0x044B, Arg0)\n

Works great in Mojave.

**Comment by hieplpvip** [comment]
Thanks. New patch added.
