### ISSUE TITLE
Keyboard backlight remains off after sleep

### ISSUE THREAD

**Issue by cowpod** [hieplpvip/AsusSMC#46]
this is not a big issue, but if i set the brightness to max, close the lid, and then wake it, the backlight remains off until the brightness is changed again.
ASUS S410U/X411U

**Comment by LeeBinder** [comment]
in Catalina, Mojave, or in both? I only experience this in Catalina (with latest v.1.2.0)

**Comment by LeeBinder** [comment]
@cowpod Henry? see my inquiry to you above.

**Comment by cowpod** [comment]
> @cowpod Henry? see my inquiry to you above.

Only in Catalina. Worked fine in Mojave for me too.

**Comment by AR-CADE** [comment]
Can someone test this version, I added a workaround for the backlight after sleep, by implementing PM events as described [here](https://developer.apple.com/library/archive/documentation/DeviceDrivers/Conceptual/IOKitFundamentals/PowerMgmt/PowerMgmt.html)
[AsusSMC-1.2.1-RELEASE.zip](https://github.com/hieplpvip/AsusSMC/files/4146648/AsusSMC-1.2.1-RELEASE.zip)

**Comment by LeeBinder** [comment]
Thank you @AR-CADE , working now as supposed in Catalina. Problem is that now backlight does not work at anymore in Mojave, which was fine before with hieplpvip's original (not tested in High Sierra yet but most likely it's the same there).

That can be for two possible reasons:
1. you only have Catalina SDK installed in Xcode so the kext won't generally work in <10.15. If so, can you please also install Mojave and High Sierra SDKs and include these macOS versions in compile options
2. if you do have Mojave and High Sierra SDKs installed and compiled for these OSes, too, can you please introduce a function which only triggers PM events with an algorithm like this:
```
if macOS version >= 10.15 then
  PM events
end if
```
Thanks for your efforts.

**Comment by AR-CADE** [comment]
Hi @LeeBinder , 

1) you are right , i only have 10.15 SDK installed, that's surely why the provided binaries don't work on  pre-catalina

can you checkout and build my fork ([link here](https://github.com/AR-CADE/AsusSMC)) with the desired SDK to see if it work 

2) the pseudo-code that you advise is already implemented, so this fix should not affect older Mac OS version :-)

I have also requested a "pull request" , see [this link](https://github.com/hieplpvip/AsusSMC/pull/62/files) for differences

**Comment by LeeBinder** [comment]
@AR-CADE great. I totally can't provide any time right now to spend in Xcode, so either we'll just wait for hieplpvip to build the kext incl. your pull request, or you simply add Mojave and High Sierra SDK for compatibility, as has hieplpvip. Be aware that many h'toshers still use Mojave.

**Comment by bliss95** [comment]
@AR-CADE Your fix works properly for Asus UX430UNR on Catalina 10.15.3.
Thank you.

**Comment by LeeBinder** [comment]
confirmed solved with latest 1.2.2 - thank you hieplpvip and AR-CADE!
