### ISSUE TITLE
something wrong with my laptop keyboard backlight

### ISSUE THREAD

**Issue by PtNan** [hieplpvip/AsusSMC#5]
I have used the DSDT patch, almost everything works fine, but my keyboard backlight still doesn't work. However if I press Fn + f3 and f4, the adjust tips does show up. Do you have any clue why I can't turn keyboard light on?

**Comment by hieplpvip** [comment]
Installation instruction has been rewritten! Please try again

**Comment by PtNan** [comment]
It works well, thanks!
