### ISSUE TITLE
Asus S510UA-BQ423 Catalina Keyboard Backlight is not working.

### ISSUE THREAD

**Issue by Nevuly** [hieplpvip/AsusSMC#52]
Hi, I tried to update my laptop to use catalina, But keyboard backlight is not working.

I used mojave a weeks ago, It is work. And I installed catalina with clean install, It is not working.

I loaded all of kexts from Clover bootloader (Not L/E), (Because of bluetooth and some fn keys)

Here is my DSDT, please check about that, and give me a solutions. (I get troubles to fix DSDT... :( )

Thanks for your work. :)

[DSDT.zip](https://github.com/hieplpvip/AsusSMC/files/3907077/DSDT.zip)

**Comment by bliss95** [comment]
Everything has started working again after updating the latest Catalina version.

didn't work before but after 10.15.2 update
All FN keys, F1 through F6
Keyboard backlight
Fn+A

My laptop: Asus UX430UNR, 16GB Ram, Corsair MP510 960GB M2 NVME
