### ISSUE TITLE
Fix to Install AsusSMCDaemon path in Catalina

### ISSUE THREAD

**Issue by Nevuly** [hieplpvip/AsusSMC#54]
Hi, sir.

I installed catalina in my vivobook, and I found issue of install AsusSMCDaemon.

in install_daemon.sh, script of cp AsusSMCDaemon, It's not copy inside of /usr/local/bin

I checked my /usr/local/bin, AsusSMCDaemon renamed and copied /usr/local/bin file. (Not directory.)

So, I edited install script to fix this problem, and finally it is work.

Here is my edit install_daemon.sh script.

[install_daemon.sh.zip](https://github.com/hieplpvip/AsusSMC/files/3993534/install_daemon.sh.zip)

**Comment by hieplpvip** [comment]
Fixed in latest commit. Thanks!
