### ISSUE TITLE
Version 1.2 not working on Mojave 10.14.6 

### ISSUE THREAD

**Issue by Denisuu** [hieplpvip/AsusSMC#55]
Hi!

I have a ASUS N580VD the keyboard backlights were working perfectly on version 1.1 but not after updating to 1.2. I know the changes are probably for Catalina so I'l stay on 1.1 for now and move to 1.2 when I upgrade to Catalina.

I just wanted to let you know.

Thanks for your hard work!

**Comment by cowpod** [comment]
Recompile with latest Lilu and VirtualSMC (and install the latest versions of those too)

**Comment by Denisuu** [comment]
I upgraded to Catalina and took the compiled version from here: 
https://github.com/hieplpvip/AsusSMC/issues/58

Everything works perfectly now!
