### ISSUE TITLE
Auto Turn-off for inactivity

### ISSUE THREAD

**Issue by soffyo** [hieplpvip/AsusSMC#69]
I don't know if this feature works on other systems. On my Asus UX331UN backlight works but the controls for keyboard backlight aren't present in system menu so I am not able to auto turn it off for inactivity. This would be a very useful feature to improve LEDs life and usability (i.e. you are watching a fullscreen video in a very dark room, the keyboard backlight disturbes your eyes from focusing on the video.)

Edit: Looking through other issues I've found that this is known under Catalina.

**Comment by tunglamvghy** [comment]
In macOS 11, I see the option that turn off the keyboard backlight after 5 seconds
![image](https://user-images.githubusercontent.com/37168923/90959100-d2399980-e4c2-11ea-8368-08bc1f8e993c.png)

**Comment by hieplpvip** [comment]
> Looking through other issues I've found that this is known under Catalina.

It used to be broken on Catalina and above. Fixed in v1.3.0
