### ISSUE TITLE
I can hardly path my dsdt

### ISSUE THREAD

**Issue by tenglendon** [hieplpvip/AsusSMC#7]

**Comment by tenglendon** [comment]
I'm so  sorry for my request.
I had read the kiwi and trying my best to path my dsdt
but i still can't figure out what's the custome code.
please help me with it
thanks
[DSDT.aml.zip](https://github.com/hieplpvip/AsusSMC/files/2729373/DSDT.aml.zip)

**Comment by tenglendon** [comment]
I'm so sorry for my request.
I had read the kiwi and trying my best to path my dsdt
but i still can't figure out what's the custome code.
please help me with it
thanks

**Comment by hieplpvip** [comment]
```
Method (SKBV, 1, NotSerialized)
{
    KBLV = Arg0 / 16
    ^^PCI0.LPCB.EC0.WRAM (0x04B1, Arg0)
    Return (Arg0)
}
```

I'm sorry that the instruction is confused.
Btw, I assume you are using Broadwell?

**Comment by tenglendon** [comment]
SIR actually I’m not sure what I’m using
My legato is ASUS ROG G752VY
It’s cpu  = Intel® Core™ i7 6700HQ.   
Intel® Skylake Core™ i7 ??

**Comment by hieplpvip** [comment]
Nevermind. Do those codes work for you?

**Comment by tenglendon** [comment]
Sir,I’m so sorry for my poor skill of pathing dsdt

5hose are my original DSDT and Pathed DSDT
Still, I can’t let my keyboard to light up

Sorry….
Sir would you kind enough to path it for me??

**Comment by hieplpvip** [comment]
I'm afraid that you have to patch it yourself.
The instruction has been rewritten, try again!

**Comment by hieplpvip** [comment]
I have made automatic patches which should work well for you!
