### ISSUE TITLE
Not loading with OpenCore bootloader

### ISSUE THREAD

**Issue by Ubsefor** [hieplpvip/AsusSMC#78]
Well, the Issue name speaks for itself: the kext can’t load when using OpenCore 0.6.0

**Comment by e-senturk** [comment]
@Ubsefor you need to recomplie this kext with latest lilu and virtualsmc kext from their sources. Only that way it will work

**Comment by Ubsefor** [comment]
> @Ubsefor you need to recomplie this kext with latest lilu and virtualsmc kext from their sources. Only that way it will work

I am using correct versions of virtualsmc, wg and lilu for this kext, at least I am sure I do, will check it a bit later, as I got rid of my experimental bootable usb drive with OpenCore and decided to stick with clover.

**Comment by hieplpvip** [comment]
@Ubsefor Please attach your EFI folder

**Comment by Ubsefor** [comment]
> @Ubsefor Please attach your EFI folder

As a matter of fact, back then I recompiled all the kexts manually, using the latest commit of lilu, and it did work, but I got several problems with power management of my iGPU, so I reverted back to stable versions

Forgot to close this issue, sorry :(
