### ISSUE TITLE
DSDT patches is not even close to my DSDT

### ISSUE THREAD

**Issue by e-senturk** [hieplpvip/AsusSMC#8]
I have Asus GL553VD laptop it's a kabylake 7700hq device all patches in new repo seems not working on my device I installed kext also it dependencies(VirtualSMC and Lilu) I can see it on ioreg. 
Here is my DSDT can you look at it?
[DSDT.aml.zip](https://github.com/hieplpvip/AsusSMC/files/2757402/DSDT.aml.zip)

**Comment by hieplpvip** [comment]
@valinor61 Are you sure that your laptop has keyboard backlight? I don't see any code related to keyboard backlight in your DSDT.

**Comment by e-senturk** [comment]
Soory for delayed reply I have red keyboard backlight. it has 3 different brightness level function keys are fn+f3 and fn+
![4add3928-e3dc-420d-8bea-a6a8cb132eb1](https://user-images.githubusercontent.com/29388244/51175384-3fd71a00-18cb-11e9-9afc-81bed135ecd7.jpg)
f4

**Comment by hieplpvip** [comment]
@valinor61 Your case is very weird, I'll do more research into it later. Now I'm pretty busy studying, sorry

**Comment by e-senturk** [comment]
Ok thanks I hope you can figure it out on your free time.

**Comment by andreszerocross** [comment]
This notebook model use HSxx of XHC controller as keyboard interface,, not PS2.

I have installed similar ROG and generations,, when i check IOREG, keyboard is ITE xxx in HSxx port of XHC. Maybe it's the issue

**Comment by hieplpvip** [comment]
@valinor61 Your laptop seems to use a different interface for keyboard backlight (which I believe something called Aura). I've found Aura port for Linux, now we just need to port it to macOS.
Will do when I have time.

For now, can you use ACPIDebug to find which EC method (i.e. Q** in DSDT) corresponding to keyboard backlight fn keys?

**EDIT:** Done some more research. As @andreszerocross, this keyboard use HID interface. It will take much time to add support.

**Comment by e-senturk** [comment]
Yes Q in DSDT is not working on my device also I have no asus aura its for rgb keyboards mine use hid interface i realized that after while I hope it can be fix I have no clue for fixing it

**Comment by hieplpvip** [comment]
@valinor61 Please send me output from gen_debug

**Comment by hieplpvip** [comment]
@valinor61 Could you send me your ioreg report?

**Comment by hieplpvip** [comment]
v2.0 added support for this laptop
