### ISSUE TITLE
AsusSMC 1.4.0 causes battery not charging 

### ISSUE THREAD

**Issue by JoK3rLeE** [hieplpvip/AsusSMC#88]
I Don't know what causes the issue, but my Asus S510UQ won't charge after updated to v1.4.0 Revert back to 1.3.1 everythings back to normal. 

[EFI.zip](https://github.com/hieplpvip/AsusSMC/files/5239347/EFI.zip)

**Comment by hieplpvip** [comment]
It's actually a new feature in v1.4.0:
```
Support battery charge threshold found on new laptops (charging stops at 80%). Can be disabled by turning off Battery Health in Energy Saver.
```

**Comment by JoK3rLeE** [comment]
OMG, I didn't saw that function in changelog, my bad :sweat_smile: and thanks!
