### ISSUE TITLE
Big sur 11.1

### ISSUE THREAD

**Issue by carlosgaros** [hieplpvip/AsusSMC#91]
Hi support big sur 11.1 ? 
Patch and install kext and not work .
Asus N550JK Big Sur 11.1 Clover 5127

**Comment by Ubsefor** [comment]
All is working correctly, check the install instructions

**Comment by carlosgaros** [comment]
look logs and find only this : 
Dec 17 10:43:33 MacBook-Pro-kamil com.apple.xpc.launchd[1] (com.hieplpvip.AsusSMCDaemon): This service is defined to be constantly running and is inherently inefficient.
Dec 17 10:43:33 MacBook-Pro-kamil com.apple.xpc.launchd[1] (com.hieplpvip.AsusSMCDaemon): The ServiceIPC key is no longer respected. Please remove it.
[DSDT.aml.zip](https://github.com/hieplpvip/AsusSMC/files/5711900/DSDT.aml.zip)

Edit ... after change use fakesmc to virtualsmc  now work f5 f6 f7 f10-f12 not work f3 f4 "keyboard backlight" .

**Comment by Ubsefor** [comment]
Please install the latest version of AsusSMC Daemon using provided scripts. The kext inself should work just fine for basic brightness and volume management, providing you have the standard asus's fn-keys layout (if not, you have to patch your DSDT to map those keys accordingly)
Also check, that you have the latest Lilu/WEG/VirtualSMC

**Comment by carlosgaros** [comment]
> Please install the latest version of AsusSMC Daemon using provided scripts. The kext inself should work just fine for basic brightness and volume management, providing you have the standard asus's fn-keys layout (if not, you have to patch your DSDT to map those keys accordingly)
> Also check, that you have the latest Lilu/WEG/VirtualSMC

Check all . All fnk key work sleep, wifi, backlight lcd,sound,disable lcd , only keyboard light not work .... DSDT send zip .

Thanks .Now all work .asus n550jk not have light sensor after patch fakeals work perfekt :)

**Comment by carlosgaros** [comment]
Thanks .Now all work .asus n550jk not have light sensor after patch fakeals work perfekt :)
