### ISSUE TITLE
Dependencies not found for kexts AsusSMC

### ISSUE THREAD

**Issue by andreademasi** [hieplpvip/AsusSMC#97]
Hi everyone, first of all thank you for this project, i'm trying to make backlight and battery health charging working but it seems that i can't manage to get AsusSMC properly loaded:
```
Dependency as.vit9696.Lilu was not found for kext com.hieplpvip.AsusSMC
Dependency as.vit9696.VirtualSMC was not found for kext com.hieplpvip.AsusSMC
```
Any ideas why AsusSMC can't find these kexts? I do have them installed
My laptop is a ZenBook UX433FN, let me know if you need more details.

**Comment by Ubsefor** [comment]
Prob. incorrect load order or kexts version, please check that. Lilu should be loaded before AsusSMC. I suggest following my kext load order:

![Снимок экрана 2021-04-17 в 13 53 52](https://user-images.githubusercontent.com/38097265/115110483-5a097200-9f84-11eb-8c8b-42db27bc2ba5.png)

**Comment by andreademasi** [comment]
Ops, you're right, totally missed that thanks.
